"""Add keyword_analyses table for caching

Revision ID: ea03dbde3e59
Revises: 
Create Date: 2026-01-17 04:33:51.854612
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ea03dbde3e59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
